DATA = [
    # --- sales / pipeline ---
    {"source": "slack", "resource": "sales-enterprise", "date": "2026-09-18",
     "text": "Customer is blocked because implementation is taking longer than expected. Third enterprise deal this month stuck on onboarding.",
     "url": "workmate://slack/sales-enterprise/1"},
    {"source": "slack", "resource": "sales-enterprise", "date": "2026-09-22",
     "text": "Lost the Acme deal to a competitor. They said pricing was fine but onboarding timeline was too long.",
     "url": "workmate://slack/sales-enterprise/2"},
    {"source": "slack", "resource": "sales-general", "date": "2026-09-10",
     "text": "Pipeline calls are down this quarter. Several reps on leave and fewer outbound sequences running.",
     "url": "workmate://slack/sales-general/1"},
    {"source": "slack", "resource": "sales-general", "date": "2026-09-25",
     "text": "Prospects keep asking for a discount, pricing objections increased after the new tier launch.",
     "url": "workmate://slack/sales-general/2"},
    {"source": "slack", "resource": "sales-general", "date": "2026-07-29",
     "text": "Two SDR roles are still unfilled since July, outbound volume has roughly halved.",
     "url": "workmate://slack/sales-general/3"},
    {"source": "documents", "resource": "q3-customer-analysis", "date": "2026-09-30",
     "text": "Q3 Customer Analysis, page 14: average onboarding time rose from 21 to 38 days after the August process change.",
     "url": "workmate://docs/q3-customer-analysis#page=14"},
    {"source": "documents", "resource": "finance-private", "date": "2026-09-28",
     "text": "Confidential: revenue forecast cut by 12 percent, pipeline coverage below target.",
     "url": "workmate://docs/finance-private/1"},
    {"source": "documents", "resource": "finance-private", "date": "2026-09-15",
     "text": "Confidential: hiring freeze approved for sales team until Q1, affects open SDR roles.",
     "url": "workmate://docs/finance-private/2"},
    {"source": "meetings", "resource": "enterprise-customer-calls", "date": "2026-09-20",
     "text": "Customer said implementation complexity is their main concern and they need a clearer onboarding plan before signing.",
     "url": "workmate://meetings/enterprise-customer-calls/7"},
    {"source": "meetings", "resource": "weekly-sales-sync", "date": "2026-09-27",
     "text": "Competitor X is undercutting on price for mid-market. Pipeline slowed mostly in enterprise segment though.",
     "url": "workmate://meetings/weekly-sales-sync/12"},
    {"source": "meetings", "resource": "weekly-sales-sync", "date": "2026-09-13",
     "text": "New sales hires take about four months to ramp, so recent hires will not contribute until Q4.",
     "url": "workmate://meetings/weekly-sales-sync/11"},

    # --- onboarding ---
    {"source": "slack", "resource": "support-escalations", "date": "2026-09-24",
     "text": "Three enterprise tickets this week about SSO setup problems during onboarding.",
     "url": "workmate://slack/support-escalations/4"},
    {"source": "documents", "resource": "onboarding-playbook-v2", "date": "2026-08-12",
     "text": "Updated onboarding playbook removes the dedicated implementation engineer for deals under 200 seats and moves data migration to the customer.",
     "url": "workmate://docs/onboarding-playbook-v2#page=3"},
    {"source": "meetings", "resource": "onboarding-retro", "date": "2026-09-29",
     "text": "Retro: moving data migration to the customer created a handoff gap and customers are waiting on answers.",
     "url": "workmate://meetings/onboarding-retro/2"},

    # --- product risks ---
    {"source": "slack", "resource": "product-eng", "date": "2026-09-19",
     "text": "API latency spikes on the reporting module during peak hours, two customers escalated.",
     "url": "workmate://slack/product-eng/8"},
    {"source": "documents", "resource": "q3-roadmap", "date": "2026-09-05",
     "text": "SSO and audit log features slipped from Q3 to Q4 due to staffing.",
     "url": "workmate://docs/q3-roadmap#page=2"},
    {"source": "meetings", "resource": "product-review", "date": "2026-09-26",
     "text": "Mobile app crash rate is up after the 4.2 release and support tickets are rising.",
     "url": "workmate://meetings/product-review/5"},

    # --- churn ---
    {"source": "slack", "resource": "cs-team", "date": "2026-09-21",
     "text": "Two mid-market accounts cancelled and cited price after Competitor X offered a lower rate.",
     "url": "workmate://slack/cs-team/6"},
    {"source": "documents", "resource": "churn-analysis", "date": "2026-09-30",
     "text": "Mid-market churn rose from 2.1 to 3.4 percent in Q3, mostly accounts under 50 seats.",
     "url": "workmate://docs/churn-analysis#page=1"},
    {"source": "meetings", "resource": "cs-weekly", "date": "2026-09-23",
     "text": "Renewal calls: customers mention missing audit logs and Competitor X pricing as reasons to leave.",
     "url": "workmate://meetings/cs-weekly/9"},
]